id = "http"
name = "http"
description = "HTTP client for .http files with Send/Show/Save buttons"
version = "0.0.2"
schema_version = 1
authors = ["tylerhanson921@gmail.com"]
repository = "https://github.com/tie304/zed-http"

[language_servers.http-lsp]
name = "HTTP LSP"
languages = ["http"]

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
commit = "e061995f0caf2fa30f68fa1fdf2c08bcbd4629a8"
